[tool.poetry]
name = "map_metrics"
version = "0.0.4"
description = "Map metrics toolkit provides a set of metrics to quantitatively evaluate trajectory quality via estimating consistency of the map aggregated from point clouds."
authors = ["Anastasiia Kornilova", "Arthur Chains"]
license = "Apache License 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
networkx = "*"
nptyping = "*"
numpy = "*"
open3d = "*"
scikit-learn = "*"

[tool.poetry.group.dev.dependencies]
types-networkx = "^3.4.2.20241115"
black = "*"
pytest = "*"
myst-nb = {version = "*", python = "^3.11"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = false
